spring:
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/benwilcock/tap-apps-config
          default-label: main
  boot:
    admin:
      client:
        url: http://spring-boot-admin.default.svc.cluster.local
        # instance:
        #   service-base-url: http://${spring.application.name}.${NAMESPACE}.${DOMAIN}
management:
  server: 
    port: 8080
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: "./logs/application.log" 
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
